# -*- coding: utf-8 -*-
"""Lab 10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1205dGjWWEEjw6js-QMnmrIvQfnJ6aAGi
"""

# LAB EXERCISE 10

## Setup Instructions
import pandas as pd
from sklearn.metrics import classification_report, mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.model_selection import train_test_split

data = {
    'hours_worked': [155, 68, 172, 49, 28, 5, 160, 51, 163, 130, 118, 111, 47, 149, 116, 52, 175, 106, 65],
    'coffee_intake': [3.2, 2.8, 5.1, 2.4, 4.5, 1.9, 3.7, 2.9, 5.2, 2.3, 6.0, 3.1, 1.8, 5.8, 2.6, 4.7, 4.9, 5.3, 4.0],
    'stress_level': [6.1, 5.4, 7.8, 5.2, 6.9, 4.8, 6.0, 5.7, 7.4, 6.3, 8.2, 5.5, 4.9, 7.6, 5.8, 6.7, 7.3, 7.9, 6.1],
    'promotion': [1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0]
}
df = pd.DataFrame(data)

# PROBLEM 1

df_tr, df_te = train_test_split(df,test_size=0.2,random_state=0)

# PROBLEM 2

problem2_model = KNeighborsClassifier(n_neighbors=3)

x_tr = df_tr[["hours_worked", "coffee_intake"]].values
y_tr = df_tr["promotion"].values
x_te = df_te[["hours_worked", "coffee_intake"]].values
y_te = df_te["promotion"].values

problem2_model.fit(x_tr,y_tr)
pred2 = problem2_model.predict(x_te)
classification_report(y_te, pred2)

# PROBLEM 3

problem3_model = KNeighborsRegressor(n_neighbors=3)

x_tr = df_tr[["hours_worked", "coffee_intake"]].values
y_tr = df_tr["promotion"].values
x_te = df_te[["hours_worked", "coffee_intake"]].values
y_te = df_te["promotion"].values

problem3_model.fit(x_tr,y_tr)
pred3 = problem3_model.predict(x_te)
mse = mean_squared_error(y_te, pred3)
r2 = r2_score(y_te, pred3)
print(mse, r2)

# EXTRA PROBLEM 1

# 1. True
# 2. True
# 3. True
# 4. True
# 5. True

# EXTRA PROBLEM 2

# 1
ind = pd.MultiIndex(levels=[["Actual"],["Positive", "Negative"]], codes=[[0,0],[0,1]])
c_matrix = pd.DataFrame(index=ind, columns=["Positive", "Negative"], data=[[45,5],[5,45]])
c_matrix

#2
# 4 total, 2 positive, 2 negative

#3
# [True Positive, False Negative]
# [False Positive, True Negative]

#4
TP = int(c_matrix["Positive"][0])
TN = int(c_matrix["Negative"][1])
FN = int(c_matrix["Negative"][0])
FP = int(c_matrix["Positive"][1])
Accuracy = (TP + TN)/(TP + FN + FP + TN)
Precision = TP/(TP + FP)
Recall = TP/(TP + FN)
print(Accuracy,
      Precision,
      Recall)

# EXTRA PROBLEM 3

# 1.  Age of a tree based on various kinds of measurements of the tree and its rings
# *2.*  How various factors interact
# 3.  Rather than using a linear value, it takes the values of the points nearest to each data point, and makes estimates from that
# 4.  Euclidean:  ((3-0)**2 + (0-4)**2)**(1/2) = 5
#     Manhattan:  abs(3-0) + abs(0-4) = 7
# 5.  Euclidean:        Measures the straight-line distance between two points in n-dimensional space.
#     Manhattan:        Measures the sum of absolute differences along each dimension/grid.