# -*- coding: utf-8 -*-
"""Lab 09

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGfvhc2Kj7Mw-CDj6k9UPhwp1G9ZZdnt
"""

# LAB EXERCISE 09

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
NUMERICAL_FEATURES = ['length', 'diameter', 'height', 'whole_weight',
'shucked_weight', 'viscera_weight', 'shell_weight',
'rings', 'age']
TARGET = 'sex'

labels = pd.read_csv('abalone_labels.csv')
measurements = pd.read_csv('abalone_measurements.csv')
abalone_data = labels.merge(measurements,on="abalone_id")

# PROBLEM 1

deletes = []
for a in abalone_data:
  for b in range(len(abalone_data[a])):
    if "I" in str(abalone_data[b:(b+1)]["sex"]):
        deletes.append(b)
    try:
      if float(abalone_data[b:(b+1)][a]) == 0.0:
        if deletes.count(b) < 1:
          deletes.append(b)
    except:
      None

abalone_cleaned = pd.DataFrame(data=abalone_data).drop(deletes)
abalone_cleaned = abalone_cleaned.dropna()
abalone_cleaned.insert(10, "age", (abalone_cleaned["rings"]+1.5))

abalone_cleaned['sex'] = abalone_cleaned['sex'].map({'F': 1, 'M': 0})
df_tr, df_te = train_test_split(abalone_cleaned, test_size=0.2, random_state=0)

# PROBLEM 2
X_tr = df_tr[NUMERICAL_FEATURES].values
Y_tr = df_tr["sex"].values

model = LogisticRegression()
model.fit(X_tr, Y_tr)

# PROBLEM 3

co = model.coef_
int = model.intercept_
max_co = max(abs(co[0]))

for a in range(len(co[0])):
  if abs(co[0][a]) == max_co:
    most_important_feature = NUMERICAL_FEATURES[a]

most_important_feature

# PROBLEM 4

Y_te = df_te["sex"].values
Y_pr = model.predict(df_te[NUMERICAL_FEATURES].values)

rep = classification_report(Y_te, Y_pr)
print(rep)

problem4_answer = "precision"