# -*- coding: utf-8 -*-
"""Lab 05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15nuLnTfGDv5tUAcvkgXOR-8b3rpd8swG
"""

# LAB EXERCISE 04

import requests
from bs4 import BeautifulSoup

# PROBLEM 01
web1 = "http://quotes.toscrape.com/page/{}/"
pages = 3
author2quotes = {}

for a in range(1,(pages+1)):
  web = web1.format(a)
  response = requests.get(web)
  soup = BeautifulSoup(response.text, "html.parser")
  books = soup.find_all("div", class_="quote")
  for b in books:
    aut = b.find_all("span")[1].small.text
    quo = [b.find_all("span")[0].text]
    try:
      author2quotes[aut] += quo
    except:
      author2quotes[aut] = quo

# PROBLEM 02
web2 = "https://catalog.northeastern.edu/course-descriptions/abrd/"
countries = []

response = requests.get(web2)
soup = BeautifulSoup(response.text, "html.parser")
books = soup.find_all("div", class_="courseblock")
for a in books:
  try:
    country = a.p.strong.text.split("—")[1].split(".")[0]
    countries.append(country)
  except:
    country = a.p.strong.text.split(": ")[1].split(".")[0]
    countries.append(country)