# -*- coding: utf-8 -*-
"""HW_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_YR-ttOxBi_hygCHdCZETt5C1GSeiFr_

# HW_01.py
"""

# import library
import csv

# PROBLEM 1
def load_and_clean_pixar_data(filename):
  pix_clean = []
  position = -1
  original_count = 0
  final_count = 0
  with open(filename, newline="") as file:
   pix = csv.DictReader(file, dialect="excel")        # Reads csv and defines df as "pix"
   for row in pix:
      original_count += 1
      if row["film"] != '':                           # If a row in the "film" column is not blank
        final_count += 1                              # Add to the final count of films
        pix_clean.append([row["number"], row["film"], row["release_date"], row["run_time"],
                          row["rotten_tomatoes"], row["metacritic"], row["film_rating"]])         # Append to "pix_clean" a list of column values for the row
   for i in range(len(pix_clean)):                    # For each film in "pix_clean"
      for j in (3,4,5):
        if pix_clean[i][j] == '':                     # If value j (numerical column) in list i of "pix_clean" is blank
          pix_clean[i].remove('')                       # Remove the blank value
          pix_clean[i].insert(j, None)                  # Replace the previously blank value with None
        else:                                         # Else, replaces the values in the numeric columns (j) with floats of the values
          pix_clean[i].insert(j, float(pix_clean[i][j]))
          pix_clean[i].remove(pix_clean[i][j+1])
  removed_count = (original_count - final_count)      # Defines count of rows removed
  clean_data_list = [{"number": i[0], "film": i[1], "release_date": i[2], "run_time": i[3], "rotten_tomatoes": i[4],
                      "metacritic": i[5], "film_rating": i[6]} for i in pix_clean]                # Defines a list of cleaned film dictionaries
  pix_data = (clean_data_list, original_count, removed_count, final_count)

  return pix_data

"""
Loads and cleans Pixar films data from a CSV file.
Removes rows with empty string value in 'film'.
Converts numeric fields ('run_time', 'rotten_tomatoes', 'metacritic') to float if they are not empty strings.

Args:
filename (str): Path to the CSV file containing Pixar films data.

Returns:
tuple: a tuple containing:
    - clean_data_list (list): List of dictionaries with cleaned film data.
    - original_count (int): Integer of original number of rows in the CSV file.
    - removed_count (int): Integer of number of rows removed due to missing data.
    - final_count (int): Integer of final number of rows after cleaning.
"""
pass #TODO implement

# PROBLEM 2
def calculate_rt_score_statistics(data):
  rt_min = []
  rt_max = []
  rt_avg = []
  sum1 = 0
  for i in data:                                  # For each film dictionary in "data"
    if i["rotten_tomatoes"] != None:              # If the value of film i's rotten tomato score is None
      rt_min.insert(0,i["rotten_tomatoes"])         # Insert 0 in the list "rt_min"
      rt_max.insert(0,i["rotten_tomatoes"])         # Insert 0 in the list "rt_max"
      rt_avg.insert(0,i["rotten_tomatoes"])         # Insert 0 in the list "rt_avg"

  for a in range(len(rt_min)-1):
    if rt_min[a] >= rt_min[a+1]:                    # If value a is >= a+1 in rt_min
      rt_min.remove(rt_min[a])                        # Remove a (the higher value)
      rt_min.insert(a, 0)                             # Replace a with 0
    else:                                           # Else
      rt_min.remove(rt_min[a+1])                    # Remove a+1 (the higher value)
      rt_min.insert(a, 0)                           # Replace a+1 with 0
  while rt_min.count(0) > 0:
	  rt_min.remove(0)                              # Remove all zeros from "rt_min"
  min_score = rt_min[0]                             # Define minimum rotten tomato score

  for b in range(len(rt_max)-1):
    if rt_max[b] <= rt_max[b+1]:
      rt_max.remove(rt_max[b])
      rt_max.insert(b, 0)
    else:
      rt_max.remove(rt_max[b+1])
      rt_max.insert(b, 0)
  while rt_max.count(0) > 0:
	  rt_max.remove(0)
  max_score = rt_max[0]

  for c in range(len(rt_avg)):
    sum1 += rt_avg[c]                               # Adds each value c of "rt_avg" to sum1
  avg_score = round((sum1)/(len(rt_avg)), 1)        # Takes and defines the average rotten tomato score
  stats = {"min_score": min_score, "max_score": max_score, "avg_score": avg_score}

  return stats


"""
Analyzes Pixar films data to calculate Rotten Tomatoes scores statistics.
    Cannot use sort(), min(), max(), mean(), or sum() functions.
    Can use round() function to round the average score to 1 decimal place.

    Args:
    data (list): List of dictionaries containing cleaned Pixar films data.

    Returns:
    dictionary: A dictionary containing the following keys and values:
        - min_score (float): Minimum Rotten Tomatoes score.
        - max_score (float): Maximum Rotten Tomatoes score.
        - avg_score (float): Average Rotten Tomatoes score rounded to 1 decimal place.
"""
pass #TODO implement

# PROBLEM 3
# SETUP
num2month = {
    '01' : 'January',
    '02' : 'February',
    '03' : 'March',
    '04' : 'April',
    '05' : 'May',
    '06' : 'June',
    '07' : 'July',
    '08' : 'August',
    '09' : 'September',
    '10' : 'October',
    '11' : 'November',
    '12' : 'December'
}
# END SETUP

def get_most_popular_release_month(data):
  months = []
  counts = []
  c = "0"
  if "-" in data[0]["release_date"]:              # If "-" is in the release data
    for i in data:                                # For film dictionary i
      splits = i["release_date"].split("-")       # Defines a list of day, month, year by splitting "-" in release date
      months.append(splits[1])                    # Appends each month value to list "months"
    for a in months:
      counts.append(months.count(a))              # Appends to "count" the number of times each month is part of the release dates
    for b in range(len(counts)-1):                # Iterates through month counts to find the max counts overall
      if counts[b] <= counts[b+1]:
        counts.remove(counts[b])
        counts.insert(b, 0)
      else:
        counts.remove(counts[b+1])
        counts.insert(b, 0)
    while counts.count(0) > 0:
	    counts.remove(0)
    total_films = counts[0]                       # Defines the highest count from "counts"
    for a in months:
      if months.count(a) == total_films:          # If the count of month a equals the max count "total_films"
        max_m = a                                 # Defines "max_m" as the month which appears most in the release dates
    most_popular_month = num2month[max_m]         # Defines name of the month value "max_m"
    releases = (most_popular_month, total_films)  # Defines tuple with month name and number of appearances
  if "/" in data[0]["release_date"]:              # If "/" is in the release data
    for i in data:
      splits = i["release_date"].split("/")
      months.append(splits[0])
    for a in months:
      counts.append(months.count(a))
    for b in range(len(counts)-1):
      if counts[b] <= counts[b+1]:
        counts.remove(counts[b])
        counts.insert(b, 0)
      else:
        counts.remove(counts[b+1])
        counts.insert(b, 0)
    while counts.count(0) > 0:
	    counts.remove(0)
    total_films = counts[0]
    for a in months:
      if months.count(a) == total_films:
        max1 = a
    max_m = c.join([" ", max1]).split(" ")[1]
    most_popular_month = num2month[max_m]
    releases = (most_popular_month, total_films)

  return releases

  """
    Returns the most popular release month and the number of films released in that month.
    max() or sort() functions cannot be used.

    Args:
    data (list): List of dictionaries containing cleaned Pixar films data.

    Returns:
    tuple: A tuple containing:
        - most_popular_month (str): The month with the highest number of films released.
                                    The month is represented as a string (e.g., "January").
        - total_films (int): The total number of films released in that month.
  """
  pass #TODO implement

# PROBLEM 4(a)
def get_longest_and_shortest_films(data):
  times1 = []
  times2 = []
  for i in data:
    if i["run_time"] != None:           # If run time is not None
      times1.append(i["run_time"])      # Append run time values to "times1"
      times2.append(i["run_time"])      # Append run time values to "times2"

  for a in range(len(times1)-1):        # Iterates through "times1" run times to find longest run time overall
    if times1[a] <= times1[a+1]:
      times1.remove(times1[a])
      times1.insert(a, 0)
    else:
      times1.remove(times1[a+1])
      times1.insert(a, 0)
  while len(times1) > 1:
	  times1.remove(0)
  for b in data:
    if b["run_time"] == times1[0]:      # If run time of a film equals the max run time
      longest_film = b["film"]            # Defines film with longest run time

  for c in range(len(times2)-1):        # Iterates through "times2" run times to find shortest run time overall
    if times2[c] >= times2[c+1]:
      times2.remove(times2[c])
      times2.insert(c, 0)
    else:
      times2.remove(times2[c+1])
      times2.insert(c, 0)
  while len(times2) > 1:
	  times2.remove(0)
  for d in data:
      if d["run_time"] == times2[0]:    # If run time of a film equals the min run time
        shortest_film = d["film"]         # Defines film with shortest run time
  run_times = {"shortest_film": shortest_film, "longest_film": longest_film}

  return run_times

"""
    Analyzes Pixar films data to find the longest and shortest films.
    max(), min(), and sort() functions cannot be used.

    Args:
    data (list): List of dictionaries containing Pixar films data.

    Returns:
    dictionary: A dictionary with the following keys and values:
        - shortest_film (str): The title of the shortest film.
        - longest_film (str): The title of the longest film.
"""
pass #TODO implement

# PROBLEM 4(b)
def get_runtime_category_counts(data):
  times1 = []
  short = []
  medium = []
  long = []
  for i in data:
    if i["run_time"] != None:
      times1.append(i["run_time"])
  for a in times1:                    # For each run time
    if a < 90:                          # If run time a is less than 90 (minutes)
      short.append(a)                     # Append a to "short"
    elif 90 <= a <= 110:                # If run time a is inclusively between 90 and 110 (minutes)
      medium.append(a)                    # Append a to "medium"
    else:                               # Else (If run time a is greater than 110 (minutes))
      long.append(a)                      # Append a to "long"
  r_times = {"short": len(short), "medium": len(medium), "long": len(long)}
  return r_times

"""
    Analyzes Pixar films data to categorize runtimes and count occurrences.

    Args:
    data (list): List of dictionaries containing Pixar films data.

    Returns:
    dictionary: A dictionary with runtime categories as keys and their counts as values.
        - 'short': Count of films with runtime < 90 minutes
        - 'medium': Count of films with runtime between 90 and 110 minutes (inclusive)
        - 'long': Count of films with runtime > 110 minutes
"""
pass #TODO implement

# PROBLEM 4(c)
def get_runtime_by_rating(data, rating):
  rt_avg = []
  sum2 = 0
  avg_r = None
  for i in data:
    if i["film_rating"] == rating:              # If film rating equals inputted "rating"
      if i["run_time"] != None:                   # If run time is not None
        rt_avg.append(i["run_time"])                # Append run time value to "rt_avg"
      if rt_avg == []:                            # If "rt_avg" is null
        avg_r = None                                # Define avg_r as None
  if rt_avg != []:                                # If "rt_avg" is not null
    for c in range(len(rt_avg)):
      sum2 += rt_avg[c]                           # Sums rating values in "rt_avg
      avg_r = round((sum2/(len(rt_avg))), 1)      # Defines "avg_r" as the average film rating
  return avg_r


"""
    Returns the average runtime of films with a specific rating (e.g., 'G', 'PG', 'PG-13', 'R').
    Returns None if the rating is not valid or if there are no films with that rating.
    Can use round() function to round the average score to 1 decimal place.

    Args:
    data (list): List of dictionaries containing Pixar films data.
    rating (str): The film rating to filter by (options can be: 'G', 'PG', 'PG-13', 'R').

    Returns:
    float: The average runtime of films with the specified rating. Rounded to 1 decimal place.
"""
pass #TODO implement

# PROBLEM 5(a)
def remove_punctuation_and_articles(lst):
  """
  Takes a list of films
  Returns a list of words from film titles, without ",", ".", "-"
  """
  punc = [",", ".", "-"]                # Defines a list of punctuation marks
  art = ("The", "A")                    # Defines a list of articles
  split = []
  for c in lst:                         # For each film title
    for d in c:                           # For each word in the film title
      if d in ("The", "A"):                 # If the word is in the "art" tuple
        c.remove(d)                           # Remove d from the film title
  for e in lst:
    for f in e:
      split.append(f)                         # Append each word of each film title to "split"
  for l in split:                      # For each word l in "split"
    for m in punc:                      # For each value m in list "punc"
      if m in l:                          # If m is in word (string) l
        split.remove(l)                     # Remove l from "split"
        split.append(l.split(m)[0])         # Add to "split" the word l without value m
  return split

def get_films_by_type(data, type_filter):
  titles = []
  films1 = []
  films2 = []
  films = []
  position = -1
  for a in (load_and_clean_pixar_data('pixar_films.csv')[0]):     # For each film dictionary
    splits = a["film"].split(" ")                                   # Defines "splits" as a list of words from the film title in film dict a
    titles.append(splits)                                           # Appends a list of words from the film title into "titles"
  for b in (load_and_clean_pixar_data('pixar_films.csv')[0]):
    films1.append([b["film"]])                                      # Appends list with film title
    films2.append([b["film"]])
    films.append([b["film"]])
  splits2 = remove_punctuation_and_articles(titles)               # Defines "splits2" as list of words from film titles, without ",", ".", "-"
  titles.reverse()                                                # Reverses order of values in "titles"
  for g in titles:                                                # For each list (film) g in titles
    for h in g:                                                   # For each film title word in list g
      try:
        int(h)                                                    # Converts numbers in a film title into integers
        g.remove(h)                                               # Removes the number from list g if it is present
      except ValueError:
        h
  for i in titles:
    for j in i:
      if splits2.count(j) > 1:                                    # If word j appears more than once in "splits2"
        splits2.remove(j)                                           # Remove j from "splits2"
        i.insert(0, "delete")                                       # Insert word "delete" in list i of "titles"
        i.remove(j)                                                 # Remove j from list i of "titles"
  for n in titles:
    while n.count("delete") > 1:                                 # While "delete" appears more than once in list n of titles
      n.remove("delete")                                          # Remove delete from list n of "titles"
  titles.reverse()                                               # Reverses order of values in "titles"
  for p in range(len(titles)):
    if "delete" in titles[p]:                                   # If word "delete" is in list p of titles
      films1.remove(films[p])                                     # Remove list p of "films" (sequels) from "films1"
    if "delete" not in titles[p]:                               # If word "delete" is not in list p of titles
      films2.remove(films[p])                                     # Remove list p of "films" (originals) from "films2"
  if type_filter == "original":                                 # If the input "type_filter" equals "original"
    o_films = [{"film": a[0]} for a in films1]                    # Defines o_films as a list of original films
    return o_films
  if type_filter == "sequel":                                   # If the input "type_filter" equals "sequel"
    s_films = [{"film": a[0]} for a in films2]                    # Defines o_films as a list of sequel films
    return s_films

"""
    Filters the Pixar films data to get a list films by type (either 'original' or 'sequel').
    Sequels are films that are not original and can be the second or later in a series.
    Use remove_punctuation_and_articles function implemented above as a helper function.

    Args:
    data (list): List of dictionaries containing Pixar films data.
    type_filter (str): The type of film to filter by ('original' or 'sequel').

    Returns:
    list: A list of dictionaries containing only original films.
"""
pass #TODO implement

# PROBLEM 5(b)
def calculate_originals_and_sequels_rt_scores(data):
  rt_avg = []
  rt2_avg = []
  films = []
  sum1 = 0
  sum2 = 0
  for b in data:                                            # For film dictionary b
    films.append({"film": b["film"]})                         # Append to "films" a dictionary of film titles
  for a in range(len(data)):
    if films[a] in (get_films_by_type(data, "original")):     # If film a is an original film
      if data[a]["rotten_tomatoes"] != None:                    # If film a rotten tomatoes score is not None
        rt_avg.append(data[a]["rotten_tomatoes"])                 # Append to "rt_avg" film a rotten tomatoes score
    elif films[a] in (get_films_by_type(data, "sequel")):     # If film a is a sequel film
      if data[a]["rotten_tomatoes"] != None:                    # If film a rotten tomatoes score is not None
        rt2_avg.append(data[a]["rotten_tomatoes"])                # Append to "rt_avg" film a rotten tomatoes score
  for c in rt_avg:                                            # For rotten tomato score c in "rt_avg"
    sum1 += c                                                   # Sum the rotten tomato scores
  avg_1 = round((sum1/(len(rt_avg))), 1)                      # Define "avg_1" as the rounded average of original film rotten tomato scores
  for d in rt2_avg:                                           # For rotten tomato score c in "rt_avg"
    sum2 += d                                                   # Sum the rotten tomato scores
  avg_2 = round((sum2/(len(rt2_avg))), 1)                     # Define "avg_1" as the rounded average of sequel film rotten tomato scores

  return {"original_avg_rt_score": avg_1, "sequel_avg_rt_score": avg_2}

"""
    Calculate the originals and sequals average Rotten Tomatoes scores.
    Uses the get_films_by_type functions to filter the data.
    Use lambda fucntion which uses sum() to calculate the average RT score.
    Can use round() function to round the average score to 1 decimal place.

    Args:
    data (list): List of dictionaries containing Pixar films data.

    Returns:
    dictionary: A dictionary with the following keys and values:
        - original_avg_rt_score (float): Average Rotten Tomatoes score for original films. Rounded to 1 decimal place.
        - sequel_avg_rt_score (float): Average Rotten Tomatoes score for sequels. Rounded to 1 decimal place.
"""
pass #TODO implement

# PROBLEM 6
def filter_top_five_films(data):
  rts = []
  mtc = []
  flm = []
  for i in data:
    if i["rotten_tomatoes"] is not None and i["metacritic"] is not None:    # If film i rotten tomato and metacritic scores are not None
      rts.insert((len(rts)),i["rotten_tomatoes"])                             # Insert the rotten tomato score
      flm.insert((len(flm)),i["film"])                                        # Insert the film title
      mtc.insert((len(mtc)),i["metacritic"])                                  # Insert the metacritic score
    else:                                                                   # Else, rotten tomato and/or metacritic score is None
      rts.insert((len(rts)),0)                                                # Insert 0 as rotten tomato score
      flm.insert((len(flm)),i["film"])                                        # Insert the film title
      mtc.insert((len(mtc)),0)                                                # Insert 0 as metacritic score
  comp = list(map(lambda x,y: ((x*(0.4))+(y*(0.6))),rts,mtc))               # Define "comp" as a list of mapped composite scores
  comps = [{"film": flm[i], "composite_score": comp[i]} for i in range(len(flm))]     # Define a dict of film title and composite score
  comps = sorted(comps,key=(lambda x: x["composite_score"]),reverse=True)[:5]         # Sort "comps" by comp score in descending order and take top 5

  return comps


"""
    Filter the top five films based on their composite scores.
    This function should use lambda function for calculating the composite score.
    Use map() and sorted() to help sort your data based on composite score.

    Args:
    data (list): List of dictionaries containing Pixar films data.

    Returns:
    list: A list of dictionaries containing the top five films with their composite scores.
          The list is sorted in descending order by composite score. The dictionary contains:
            - 'film': The title of the film.
            - 'composite_score': The composite score of the film.
"""
pass #TODO implement

if __name__ == "__main__":
    print("HW 01: PIXAR FILMS DATA ANALYSIS")

    # Use this main function to call your functions and test them.

    # PROBLEM 1 - calling
    print('\nProblem 1')
    clean_data_list, original_count, removed_count, final_count = load_and_clean_pixar_data('pixar_films.csv')
    print(f"Original_Count: {original_count}, Removed_Count: {removed_count}, Final_Count: {final_count}")

    # PROBLEM 2 - calling
    print("\nProblem 2")
    min_score, max_score, avg_score = calculate_rt_score_statistics(load_and_clean_pixar_data('pixar_films.csv')[0])["min_score"], calculate_rt_score_statistics(load_and_clean_pixar_data('pixar_films.csv')[0])["max_score"], calculate_rt_score_statistics(load_and_clean_pixar_data('pixar_films.csv')[0])["avg_score"]
    print(f"Min_Score: {min_score}, Max_Score: {max_score}, Avg_Score: {avg_score}")

    # Problem 3 - calling
    print("\nProblem 3")
    most_popular_month, total_films = get_most_popular_release_month(load_and_clean_pixar_data('pixar_films.csv')[0])
    print(f"Most_Popular_Month: {most_popular_month}, Total_Films: {total_films}")

    # Problem 4 - calling
    print("\nProblem 4")
    shortest_film, longest_film = get_longest_and_shortest_films(load_and_clean_pixar_data('pixar_films.csv')[0])["shortest_film"], get_longest_and_shortest_films(load_and_clean_pixar_data('pixar_films.csv')[0])["longest_film"]
    print(f"Shortest_Film: {shortest_film}, Longest_Film: {longest_film}")
    short, medium, long = get_runtime_category_counts(load_and_clean_pixar_data('pixar_films.csv')[0])["short"], get_runtime_category_counts(load_and_clean_pixar_data('pixar_films.csv')[0])["medium"], get_runtime_category_counts(load_and_clean_pixar_data('pixar_films.csv')[0])["long"]
    print(f"Short: {short}, Medium: {medium}, Long: {long}")
    avg1, avg2, avg3, avg4 = get_runtime_by_rating(load_and_clean_pixar_data('pixar_films.csv')[0], "G"), get_runtime_by_rating(load_and_clean_pixar_data('pixar_films.csv')[0], "PG"), get_runtime_by_rating(load_and_clean_pixar_data('pixar_films.csv')[0], "PG-13"), get_runtime_by_rating(load_and_clean_pixar_data('pixar_films.csv')[0], "R")
    print(f"G_Runtime: {avg1}, PG_Runtime: {avg2}, PG13_Runtime: {avg3}, R_Runtime: {avg4}")


    # Problem 5 - calling
    print("\nProblem 5")
    o_films, s_films = get_films_by_type((load_and_clean_pixar_data('pixar_films.csv')[0]),"original"), get_films_by_type((load_and_clean_pixar_data('pixar_films.csv')[0]),"sequel")
    print(f"Original: {o_films}, Sequel: {s_films}")
    avg_1, avg_2 = calculate_originals_and_sequels_rt_scores(load_and_clean_pixar_data('pixar_films.csv')[0])["original_avg_rt_score"], calculate_originals_and_sequels_rt_scores(load_and_clean_pixar_data('pixar_films.csv')[0])["sequel_avg_rt_score"]
    print(f"Original_RT_Score: {avg_1}, Sequel_RT_Score: {avg_2}")

    # PROBLEM 6 - calling
    print("\nProblem 6")
    comps = filter_top_five_films(load_and_clean_pixar_data('pixar_films.csv')[0])
    print(f"{comps}")