# -*- coding: utf-8 -*-
"""Lab 03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mte1wKMlTYIwopjiYn8mzBdcWHXJF0PN
"""

# LAB EXERCISE 03

# PROBLEM 01

employees = [{"name": "Alice", "department": "Engineering", "years_experience":5},
{"name": "Ann", "department": "Marketing", "years_experience": 4},
{"name": "Ben", "department": "Engineering", "years_experience":2},
{"name": "Bob", "department": "Engineering", "years_experience":6},
{"name": "Eve", "department": "HR", "years_experience": 3},]

filtered_employees = [i["name"] for i in employees if i["department"] == "Engineering" and i["years_experience"] > 3]
filtered_employees

#filtered_employees = []
#for i in range(len(employees)):
#  if employees[i]["department"] == "Engineering":
#     if employees[i]["years_experience"] > 3:
#        filtered_employees.append(employees[i]["name"])
#print(filtered_employees)

# PROBLEM 02

pairs = [(5,2), (1,4), (3,1), (2,9)]


triples = [(i[0], i[1], (i[0]*i[1])) for i in pairs]
triples

# PROBLEM 03

pairs = [(5,2), (1,4), (3,1), (2,9)]

p3_pairs = sorted(pairs, key=(lambda x: x[1]))
p3_pairs

# PROBLEM 04

pairs = [(5,2), (1,4), (3,1), (2,9)]

p4_pairs = sorted(pairs, key=(lambda x: (x[0]+x[1])), reverse=True)
p4_pairs