# -*- coding: utf-8 -*-
"""Lab 07

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fR63ut-giRIwYFktbW2RiWPYScwrUETK
"""

# LAB EXERCISE 07

# PROBLEM 01

def zscore(lst1):
  if lst1 == []:
    return None
  else:
    avg = sum(lst1)/(len(lst1))
    sd = 0
    for a in lst1:
      sd += ((a-avg)**2)/len(lst1)
    sd = sd**(1/2)
    z = []
    for b in lst1:
      z.append((b-avg)/sd)
    return z

# PROBLEM 02

def min_max_scaling(lst2):
  if lst2 == []:
    return None
  else:
    min_num = min(lst2)
    max_num = max(lst2)
    min_max = []
    for i in lst2:
      min_max.append((i - min_num)/(max_num - min_num))
    return min_max

# PROBLEM 03

import pandas as pd
df = pd.DataFrame({
    "A": [i for i in range(1,6)],
    "B": [4, None, None, None, None],
    "C": ["High", "Medium", "Medium", "High", "Low"]
})

deletes = []
for i in df:
  if df[i].isnull().sum() > 0:
    if deletes.count(i) < 1:
      deletes.append(i)

df_col_cleaned = pd.DataFrame(data=df).drop(columns=deletes)
df_col_cleaned

deletes2 = []
for i in df:
  for j in range(len(df[i])):
    if df[j:(j+1)][i].isnull().sum() > 0:
      if deletes2.count(j) < 1:
        deletes2.append(j)

df_row_cleaned = pd.DataFrame(data=df).drop(deletes2)
df_row_cleaned

# PROBLEM 04

df_encoded = pd.get_dummies(df_col_cleaned, columns=["C"])
df_encoded

# EXTRA PROBLEM 01

# 1. False
# 2. *False*
# 3. False
# 4. False
# 5. True   -   Also line plot