# -*- coding: utf-8 -*-
"""season

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175vweFp-LA5oU-uF84EUvVvllFQtv5FD
"""

# import library
import csv
import pandas as pd
import matplotlib.pyplot as plt

# import class
from team import Team

WSL_goals = pd.read_csv('wsl_goals_2324.csv')
WSL_goals

# PART 1 - Q1

def most_goals(team_lst):
  total_goals = []
  for b in range(len(team_lst)):
    teams = Team(team_lst[b])                         # Defining Team() class "name" input
    for c in range(1,23):
      if str(WSL_goals[str(c)][b]) != "nan":
        teams.add_goals(int(WSL_goals[str(c)][b]))    # Inputing a given teams goals, if listed
      else:
        teams.add_goals(0)                            # Unlisted goals are 0
    total_goals.append(teams.get_total_goals())       # Appending a list of total goals for each team
  max_goal = max(total_goals)                         # Finding the highest value of total goals scored
  for d in range(len(total_goals)):                   # Finding the team which has the highest number of total goals
    if total_goals[d] == max_goal:
      team_max = team_lst[d]
  return team_max

# PART 1 - Q2

def avg_total_goals(team_lst):
  total_goals = []
  for b in range(len(team_lst)):
    teams = Team(team_lst[b])                         # Defining Team() class "name" input
    for c in range(1,23):
      if str(WSL_goals[str(c)][b]) != "nan":
        teams.add_goals(int(WSL_goals[str(c)][b]))    # Inputing a given teams goals, if listed
      else:
        teams.add_goals(0)                            # Unlisted goals are 0
    total_goals.append(teams.get_total_goals())       # Appending a list of total goals for each team
  avg_tot_goals = teams.get_avg(total_goals)          # Using defined average function and list of total goals from Q1 to find the mean of total goals scored by all teams
  avg_tot_goals = round(avg_tot_goals,2)
  return avg_tot_goals

# PART 1 - Q3

def var_total_goals(team_lst):
  total_goals = []
  for b in range(len(team_lst)):
    teams = Team(team_lst[b])                                              # Defining Team() class "name" input
    for c in range(1,23):
      if str(WSL_goals[str(c)][b]) != "nan":
        teams.add_goals(int(WSL_goals[str(c)][b]))                         # Inputing a given teams goals, if listed
      else:
        teams.add_goals(0)                                                 # Unlisted goals are 0
    total_goals.append(teams.get_total_goals())                            # Appending a list of total goals for each team
  var_tot_goals = teams.get_var(total_goals,avg_total_goals(team_lst))     # Using defined variance function, list of total goals from Q1 and mean from Q2 to find variance of total goals scored by all teams
  var_tot_goals = round(var_tot_goals,2)
  return var_tot_goals

# PART 1 - Q4
def sd_total_goals(team_lst):
  teams = Team(team_lst[0])                                     # Defining Team() class "name" input
  sd_tot_goals = teams.get_sd(var_total_goals(team_lst))        # Using defined standard deviation function and variance from Q3 to find the standard deviation of total goals scored by all teams
  sd_tot_goals = round(sd_tot_goals,2)
  return sd_tot_goals

# PART 1 - Q5

def get_median(team_name):
  for a in range(len(WSL_goals["team"])):
    if WSL_goals["team"][a] == team_name:
      team_num = a                                # Defining what position "Arsenal" has in list of teams

  ars = Team(team_name)                           # Defining Team() class "name" input as "Arsenal"
  for b in range(1,23):
    goal = WSL_goals[str(b)][team_num]            # Assigning each goal by Arsenal before appending it to ars.goals
    if str(goal) != "nan":
      ars.add_goals(int(goal))                    # Inputing team goals, if listed
    else:
      ars.add_goals(0)                            # Unlisted goals are 0
  g_list = sorted(ars.goals)                      # Sorting list of Arsenal's goals in order to determine median
  while len(g_list) > 2:                          # If there is an even number in values in the list of goals, all values but the two medians are removed
                                                  # If there is an odd number of values in the list of goals, all values but the median are removed
    g_list.remove(g_list[0])
    g_list.remove(g_list[(len(g_list)-1)])
  med = round(sum(g_list)/(len(g_list)),2)        # If there are two medians, the average of the two is taken. If there is one median, the average is itself.
  return med

# PART 1 - Q6

def get_mode(team_name):
  for a in range(len(WSL_goals["team"])):
    if WSL_goals["team"][a] == team_name:
      t_num = a                                           # Defining what position "Tottenham Hotspur" has in list of teams

  th = Team(team_name)                                    # Defining Team() class "name" input as "Tottenham Hotspur"
  for b in range(1,23):
    goal = WSL_goals[str(b)][t_num]                       # Assigning each goal by Tottenham Hotspur before appending it to ars.goals
    if str(goal) != "nan":
      th.add_goals(int(goal))                             # Inputing team goals, if listed
    else:
      th.add_goals(0)                                     # Unlisted goals are 0

  counts = []
  for c in th.goals:
    counts.append(th.goals.count(c))                      # Appending the count of each goal scored by Tottenham Hotspur
  for d in range(len(th.goals)):                          # Finding the number of goals which has the highest count (the mode of the goals)
    if counts[d] == max(counts):
      mode = th.goals[d]
  return mode

# PART 1 - Q7

def most_consistent_scoring(team_lst):
  con_list = []
  for b in range(len(team_lst)):
    team = Team(team_lst[b])                      # Defining Team() class "name" input
    for c in range(1,23):
      goal = WSL_goals[str(c)][b]                 # Assigning each goal by the given team before appending it to team.goals
      if str(goal) != "nan":
        team.add_goals(int(goal))                 # Inputing a given teams goals, if listed
      else:
        team.add_goals(0)                         # Unlisted goals are 0
    avg = team.get_avg(team.goals)                # Finding the average number of goals by the given team
    var = team.get_var(team.goals,avg)            # Finding the variance in the number of goals by the given team
    sd = team.get_sd(var)                         # Finding the standard deviation of the number of goals by the given team
    con = sd/avg                                  # Finding the coeffecient of variance = standard_deviation/mean
    con_list.append(con)                          # Appending the coeffecient of variance for each team to a list

  min_con = min(con_list)                         # Finding the lowest coefficient of variance
  for f in range(len(con_list)):                  # Finding the team which has the lowest coeffecient of variance, which determines the most consistent goal-scoring pattern
    if con_list[f] == min_con:
      min_con = team_lst[f]
  return min_con

# PART 1 - Q8

def longest_streak(team_lst):
  max_streak = []
  for b in range(len(team_lst)):
    sum1 = 0
    streaks = []
    team = Team(team_lst[b])                      # Defining Team() class "name" input
    for c in range(1,23):
      goal = WSL_goals[str(c)][b]                 # Assigning each goal by the given team before appending it to team.goals
      if str(goal) != "nan":
        team.add_goals(int(goal))                 # Inputing a given teams goals, if listed
      else:
        team.add_goals(0)                         # Unlisted goals are 0
    for d in team.goals:
      if d >= 2:                                  # Adding each goal > 2 to the count/sum of streaks
        sum1 += 1
      else:
        streaks.append(sum1)                      # If the number of goals is < 2, append the streak length before this goal to a list of streaks
        sum1 = 0                                  # If the number of goals is < 2, reset the streak count
    streaks.append(sum1)                          # Append the last streak to the list of streaks for the given team
    max_streak.append(max(streaks))               # Append the maximum streak for each team to a list

  for e in range(len(max_streak)):                # Finding the team which has the maximum streak
    if max_streak[e] == max(max_streak):
      max_s = team_lst[e]
  return max_s

# PART 1 - Q9

def most_improved(team_lst):
  diffs = []
  for b in range(len(team_lst)):
    var1 = []
    team = Team(team_lst[b])                      # Defining Team() class "name" input
    for c in range(1,12):
      goal = WSL_goals[str(c)][b]                 # Assigning each goal from games 1 to 11 by the given team before appending it to team.goals
      if str(goal) != "nan":
        team.add_goals(int(goal))                 # Inputing a given teams goals, if listed
      else:
        team.add_goals(0)                         # Unlisted goals are 0
    avg1 = team.get_avg(team.goals)               # Using the defined average function to get the average of the goals from games 1 to 11
    for e in range(12,23):
      goal = WSL_goals[str(e)][b]                 # Assigning each goal from games 12 to 22 by the given team before appending it to team.goals
      if str(goal) != "nan":
        team.add_goals(int(goal))
      else:
        team.add_goals(0)
    avg2 = team.get_avg(team.goals[11:22])        # Using the defined average function to get the average of the goals from games 12 to 22
    diffs.append(avg2-avg1)                       # Appending the difference between second half average and first half average for each team

  for g in range(len(diffs)):                     # Finding the team which has the maximum difference between second half average goals and first half average goals
    if diffs[g] == max(diffs):
      max_diff = team_lst[g]
  return max_diff

# PART 2

def cumulative_goals(team_lst):                                 # Creates a list of lists with the cumulative goals of every team. Each list entry is a sum of goals from the current match and all prior matches.
  goals_list1 = []
  goals_list2 = []
  for b in range(len(team_lst)):
    teams = Team(team_lst[b])                                   # Defining Team() class "name" input
    for c in range(1,23):
      if str(WSL_goals[str(c)][b]) != "nan":
        teams.add_goals(int(WSL_goals[str(c)][b]))              # Inputing a given teams goals, if listed
      else:
        teams.add_goals(0)                                      # Unlisted goals are 0
      teams.move_next()                                         # Using defined function to increase the value of teams.x by each additional goal in team.goals for each team
      goals_list1.append(teams.x)                               # Appending every new teams.x for each team, resulting in a list of increasing goal totals for all teams

  for d in range(len(team_lst)):
    goals_list2.append((goals_list1[22*d:22*(d+1)]))            # Creating a list of lists with every team.x for each team

  return goals_list2

def plot_teams(team_lst,team_abbrevs,colors_lst):               # Creates a scatter plot of the teams' total_goals by each match
  goals_list2 = cumulative_goals(team_lst)
  for d in range(len(goals_list2[0])):                          # for d in range(22)    (number of matches)
    for e in range(len(team_lst)):                              # for e in range(12)    (number of teams)
      teams = Team(team_lst[e])                                 # Defining Team() class "name" input, where each new iteration of loop is a new team and an emptied teams.goals
      teams.add_goals(goals_list2[e][d])                        # Appending the given team's total goals by match d to the teams.goals
      teams.y = team_abbrevs[e]                                 # Assigning the y-value, teams.y, of the graph as the given team's abbreviation
      teams.color = colors_lst[e]                               # Assigning the corresponding team color for the given team
      teams.move_next()                                         # Defining teams.x as the value in teams.goals (the given team's total goals by match d)
      teams.draw()
    plt.xlim(0, ( max([max(goals_list2[i]) for i in range(len(team_lst))]) + 5))                      # Defining limit as 5 above maximum of total goals amongst all teams (maximum of list of total_goals from final match)
    plt.title("WSL 2023-2024 Season")
    plt.xlabel("Number of Goals")
    plt.ylabel("WSL Teams")
    plt.show()

def main():
  WSL_goals = pd.read_csv('wsl_goals_2324.csv')
  teams_list = []
  for a in range(len(WSL_goals["team"])):
    teams_list.append(WSL_goals["team"][a])               # List of team names
  colors_list = ["red","skyblue","blue","maroon","dodgerblue","royalblue","gold","firebrick","skyblue","goldenrod","navy","red"]
  teams_abbrev = ["ARS","AVL","BHA","BCFC","CHE","EFC","LCFC","LFC","MCFC","MUFC","THFC","WHU"]

  # Q1 - calling
  print('\nQ1')
  most_goals_scored = most_goals(teams_list)
  print(f"Most goals scored by:   {most_goals_scored}")

  # Q2 - calling
  print('\nQ2')
  avg_all_goals = avg_total_goals(teams_list)
  print(f"Average of all teams' total goals:    {avg_all_goals}")

  # Q3 - calling
  print('\nQ3')
  var_all_goals = var_total_goals(teams_list)
  print(f"Variance of all teams' total goals:   {var_all_goals}")

  # Q4 - calling
  print('\nQ4')
  sd_all_goals = sd_total_goals(teams_list)
  print(f"Standard deviation of all teams' total goals:   {sd_all_goals}")

  # Q5 - calling
  print('\nQ5')
  med = get_median("Arsenal")
  print(f"Median of Arsenal's goals:    {med}")

  # Q6 - calling
  print('\nQ6')
  mode = get_mode("Tottenham Hotspur")
  print(f"Mode of Tottenham Hotspur's goals:    {mode}")

  # Q7 - calling
  print('\nQ7')
  scoring_consistence = most_consistent_scoring(teams_list)
  print(f"Median of Arsenal's goals:    {scoring_consistence}")

  # Q8 - calling
  print('\nQ8')
  streak = longest_streak(teams_list)
  print(f"Median of Arsenal's goals:    {streak}")

  # Q9 - calling
  print('\nQ9')
  score_improvement = most_improved(teams_list)
  print(f"Median of Arsenal's goals:    {score_improvement}")

  # PART 2 - calling
  print('\nPART 2')
  print(f"Cumulative Goals:")
  cumulative_goals_list = cumulative_goals(teams_list)
  goals_plot = plot_teams(teams_list,teams_abbrev,colors_list)


if __name__ == "__main__":
    main()