# -*- coding: utf-8 -*-
"""team

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bYRzZ_KSUEz1vwsE3vMKn_MKc_zHGoWM
"""

import csv
import pandas as pd
import matplotlib.pyplot as plt

class Team():
  def __init__(self,name):
    self.name = name
    self.goals = []
    self.x = 0
    self.y = 0
    self.color = "green"
  def draw(self):
    plt.scatter(self.x, self.y, c=self.color, marker="D")
  def add_goals(self,goals):
    self.goals.append(goals)
  def get_total_goals(self):
    sum_g = 0
    for a in self.goals:
      sum_g += a
    return sum_g
  def move_next(self):
    self.x += self.goals.pop(len(self.goals)-1)
  def get_avg(self,goals_list):
    sum1 = 0
    for a in goals_list:
      sum1 += a
    avg1 = (sum1)/(len(goals_list))
    return avg1
  def get_var(self,goals_list,avg2):
    var1 = 0
    for a in goals_list:
      var1 += (a - avg2)**2/(len(goals_list))
    return var1
  def get_sd(self,var2):
    sd = (var2)**(1/2)
    return sd


  def __str__(self):
    total = self.get_total_goals()
    return (f'Team: {self.name}\n'
            f'Goals: {self.goals}\n'
            f'Total Goals: {total}')