# -*- coding: utf-8 -*-
"""#2 DS 2500 - Final Project Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5mlQPy3AQExEUBwZh2SBrD1J7iYu0Md

**DS 2500 - Final Project Code**
"""

# Import Libraries

import pandas as pd
import seaborn as sns
from numpy import transpose
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import mean_squared_error, r2_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer

# Function: Reading csvs and merging the resulting DataFrames

def merge_dfs(df1, df2, shared_columns, suffix1, suffix2):     # TAKES two csv files, name(s) of their shared column(s), and column suffix names, RETURNS a merged DataFrame of the two csv files
  merged_df = df1.merge(df2,on=shared_columns, suffixes=(suffix1,suffix2))      # Merges "df1" and "df2" on "shared_columns" with inputted suffixes and stores it as "merged_df"
  return merged_df

# Function: Selects columns in the inputted DataFrame with values from 2024

def select_columns(df):               # TAKES a DataFrame, RETURNS a list of the defined shared columns between merged DataFrames plus the columns with data from 2024
  year_range = ["2019", "2020", "2021", "2022", "2023", "2024", "2025"]                   # Defines years covered by new DataFrame
  cols = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]
  for a in df:                        # Iterates through each column in the inputted DataFrame
    for b in year_range:
      if b in a:                      # If 2024 is in the column name, which is a string of the date during which the data was collected
        cols.append(a)           # Add the columns with data from 2024 to the list of shared columns
  return cols

# Function: Cleans data within a DataFrame by eliminating rows with 0 and null values

def clean_df(df):                                       # TAKES a DataFrame, RETURNS a cleaned version of the DataFrame without rows containing null/empty or 0 values
  deletes = []
  for a in df:                                          # Iterates through each title in the inputted DataFrame
    for b in range(len(df)):                            # Iterates through the number of rows in "df"
      try:
        if float(df[a][b]) == 0.0:                # If float of the value in column a, row b is 0.0 and if the row is not already in list "deletes", add row b to "deletes"
          if deletes.count(b) < 1:
            deletes.append(b)
      except:
        None

  df_cleaned = pd.DataFrame(data=df).drop(deletes)      # Drop the rows that contain 0s, which are stored in list "deletes", and store new DataFrame as "df_cleaned"
  df_cleaned = df_cleaned.dropna()                      # Drop null values in "df_cleaned"
  return df_cleaned

col_titles = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName", "For-Sale_Inventory", "Home_Value_Index", "Mean_Sale_Price", "Median_Days_to_Close",
              "Median_Sale_Price", "New_Listings", "Newly_Pending_Listings", "Sales_Count"]

FSI_df = pd.read_csv("For-Sale_Inventory.csv")
FSI_df = FSI_df[select_columns(FSI_df)]                     # Redefines the DataFrame with only shared columns and columns from

HVI_df = pd.read_csv("Home_Value_Index.csv")
HVI_df = HVI_df[select_columns(HVI_df)]

MeanSP_df = pd.read_csv("Mean_Sale_Price.csv")
MeanSP_df = MeanSP_df[select_columns(MeanSP_df)]

MedDC_df = pd.read_csv("Median_Days_to_Close.csv")
MedDC_df = MedDC_df[select_columns(MedDC_df)]

MedSP_df = pd.read_csv("Median_Sale_Price.csv")
MedSP_df = MedSP_df[select_columns(MedSP_df)]

NL_df = pd.read_csv("New_Listings.csv")
NL_df = NL_df[select_columns(NL_df)]

NPL_df = pd.read_csv("Newly_Pending_Listings.csv")
NPL_df = NPL_df[select_columns(NPL_df)]

SC_df = pd.read_csv("Sales_Count.csv")
SC_df = SC_df[select_columns(SC_df)]

num_cols = [len(FSI_df.transpose()), len(HVI_df.transpose()), len(MeanSP_df.transpose()), len(MedDC_df.transpose()), len(MedSP_df.transpose()),
            len(NL_df.transpose()), len(NPL_df.transpose()), len(SC_df.transpose())]
num_cols = [i-5 for i in num_cols]

# Reads and merges 8 csvs for each feature, stores the csvs as a DataFrame, selects columns from 2024, and cleans the final DataFrame using "clean_df" function

shared_cols = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]                                 # Defines columns shared by csvs
df1 = merge_dfs(FSI_df, HVI_df, shared_cols, "_FSI", "_HVI")
df2 = merge_dfs(MeanSP_df, MedDC_df, shared_cols, "_MeanSP", "_MDC")
df3 = merge_dfs(MedSP_df, NL_df, shared_cols, "_MedSP", "_NL")
df4 = merge_dfs(NPL_df, SC_df, shared_cols, "_NPL", "_SC")
housing_df = df1.merge(df2, on=shared_cols, suffixes=("_a", "_b")).merge(df3, on=shared_cols, suffixes=("_c", "_d")).merge(
              df4, on=shared_cols, suffixes=("_e", "_f"))               # Merges the four different DataFrames into one on "shared_cols"

df_cleaned = clean_df(housing_df)

col_values = []
min_range = 5
max_range = 5
for a in num_cols:
  max_range += a
  val = []
  for b in range(len(df_cleaned)):
    sum = 0
    for c in range(min_range, max_range):
      sum += float(df_cleaned.iloc[b,c])
    val.append(sum/(max_range-min_range))
  col_values.append(val)
  min_range += a

feature_setup = {col_titles[5+i]: col_values[i] for i in range(len(col_values))}    # Creates a dictionary iterating through range(8) (number of features) with key as (5+i) in "col_titles" (8 features, excluding first 5 cols), values for each key as each list (containing each row's feature averages) in "col_values"
features_df = pd.DataFrame(data=feature_setup)                                      # Creates a DataFrame of the 8 features with new titles as listed in "col_titles"
housing_cleaned = df_cleaned[col_titles[0:5]].join(features_df, how="right")        # Defines a new DataFrame joining first 5 columns of "df_cleaned" with "features_df" using the index defined in "features_df"

# Creates a correlation matrix, finds the strongest and weakest correlations between numerical features (not "RegionID", "Sales_Count") and "Sales_Count"

correlation = housing_cleaned.corr(numeric_only=True)         # Standard correlation matrix "correlation" of the numerical feautures in "housing_cleaned" DataFrame
titlesx = [i if i == "Sales_Count" else " " for i in correlation]                           # List of x-axis titles (only correlation for "Sales_Count")
titlesy = [i if i != "Sales_Count" and i != "RegionID" else " " for i in correlation]       # List of y-axis titles (excludes correlation of "Sales_Count", "RegionID" to "Sales_Count")
strongest_correlation = ""
weakest_correlation = ""
max_correl = max(abs(correlation["Sales_Count"][1:9]))
min_correl = min(abs(correlation["Sales_Count"][1:9]))
for n in range(1,(len(correlation)-1)):                                        # Iterates through number of features correlated with "Sales_Count" (not "RegionID", "Sales_Count")
  if abs(float(correlation.iloc[len(correlation)-1, n])) == max_correl:      # If a value in "Sales_Count" row of correlation matrix = maximum value of the row (not "RegionID", "Sales_Count")
    strongest_correlation = titlesy[n]                                            # Set "strongest_correlation" to the row title n on y-axis of the correlation matrix
  if abs(float(correlation.iloc[len(correlation)-1, n])) == min_correl:      # If a value in "Sales_Count" row of correlation matrix = minimum value of the row (not "RegionID", "Sales_Count")
    weakest_correlation = titlesy[n]                                              # Set "weakest_correlation" to the row title n on y-axis of the correlation matrix
print("Strongest Correlation:\t", strongest_correlation)
print("Weakest Correlation:\t", weakest_correlation)
correlation

# Creates a heatmap of the correlation matrix, labels the heatmap including labels of the weakest and strongest correlations

correlation = housing_cleaned.corr(numeric_only=True)                 # Standard correlation matrix "correlation" of the numerical feautures in "housing_cleaned" DataFrame
titlesx = [i if i == "Sales_Count" else " " for i in correlation]                         # List of x-axis titles (only correlation for "Sales_Count")
titlesy = [i if i != "Sales_Count" and i != "RegionID" else " " for i in correlation]     # List of y-axis titles (excludes correlation of "Sales_Count", "RegionID" to "Sales_Count")

fig, axis = plt.subplots()                                                                # Defining a figure and its subplots/axes
axis.imshow(correlation)                                                                  # Plots the inputted correlation matrix
correl_nums = []
for h in range(len(correlation)):                                                         # Iterates through the number of rows in the correlation matrix
  for i in correlation:                                                                   # Iterates through the titles in the correlation matrix
    correl_nums.append(round(float(correlation[i].iloc[h]),3))                            # Adds to empty list "correl_nums" the values in the correlation matrix by row
for j in range(len(correlation)):                                                         # Iterates through the number of rows in the correlation matrix
  for k in range(len(correlation)):                                                       # Iterates through the number of rows in the correlation matrix
    text = axis.text(x=(k-.35), y=(j+.1), s=(correl_nums[k+10*j]),fontsize=7.5)                        # Adds the value (s) in the correlation matrix at coordinate (x,y) by row
axis.set_xticks(range(len(titlesx)),labels=titlesx)                                       # Sets the x-axis labels based on the labels list "titlesx"
axis.set_yticks(range(len(titlesy)),labels=titlesy)                                       # Sets the y-axis labels based on the labels list "titlesy"
y_val1 = 0
y_val2 = 0
for n in range(len(titlesy)):                                                             # Iterates through list of column titles of the correlation matrix in "titlesy"
  if titlesy[n] == strongest_correlation:                                                 # If nth title in "titlesy" equals "strongest_correlation"
    y_val1 = n                                                                            # Set "y_val1" to row l on y-axis of the correlation matrix
  if titlesy[n] == weakest_correlation:                                                   # If nth title in "titlesy" equals "weakest_correlation"
    y_val2 = n                                                                            # Set "y_val2" to row l on y-axis of the correlation matrix
axis.text(x=(len(correlation)),y=(y_val1),s="strongest correlation")                      # Adds text "strongest correlation" at point (x,y)
axis.text(x=(len(correlation)),y=(y_val2),s="weakest correlation")                        # Adds text "weakest correlation" at point (x,y)
plt.show()

# Features and target
X_lin = housing_cleaned.drop(
    ["RegionID", "RegionName", "RegionType", "StateName", "Sales_Count"],
    axis=1
)
y_lin = housing_cleaned["Sales_Count"]

# Train/test split
X_train_lin, X_test_lin, y_train_lin, y_test_lin = train_test_split(
    X_lin, y_lin, test_size=0.2, random_state=42
)

# Pipeline: Imputer -> Scaler -> Linear Regression
linreg_pipeline = make_pipeline(
    SimpleImputer(strategy="median"),
    MinMaxScaler(),
    LinearRegression()
)

linreg_pipeline.fit(X_train_lin, y_train_lin)
y_pred_lin = linreg_pipeline.predict(X_test_lin)

print("LINEAR REGRESSION RESULTS")
print("R²:", r2_score(y_test_lin, y_pred_lin))

mse = mean_squared_error(y_test_lin, y_pred_lin)
rmse = mse ** 0.5
print("RMSE:", rmse)

# Extract coefficients from the final step of the pipeline
linreg_model = linreg_pipeline.named_steps["linearregression"]
linreg_coeffs = pd.DataFrame({
    "Feature": X_lin.columns,
    "Coefficient": linreg_model.coef_
}).sort_values("Coefficient", ascending=False)

print(linreg_coeffs)

median_sales = housing_cleaned["Sales_Count"].median()
housing_cleaned["High_Sales"] = (
    housing_cleaned["Sales_Count"] >= median_sales
).astype(int)

X_log = housing_cleaned.drop(
    ["RegionID", "RegionName", "RegionType", "StateName", "Sales_Count", "High_Sales"],
    axis=1
)
y_log = housing_cleaned["High_Sales"]

X_train_log, X_test_log, y_train_log, y_test_log = train_test_split(
    X_log, y_log, test_size=0.2, random_state=42
)

logreg_pipeline = make_pipeline(
    SimpleImputer(strategy="median"),
    MinMaxScaler(),
    LogisticRegression(max_iter=500)
)

logreg_pipeline.fit(X_train_log, y_train_log)
y_pred_log = logreg_pipeline.predict(X_test_log)

print("LOGISTIC REGRESSION RESULTS\n")
print("Confusion Matrix:\n", confusion_matrix(y_test_log, y_pred_log))
print("\nClassification Report:\n", classification_report(y_test_log, y_pred_log))

logreg_model = logreg_pipeline.named_steps["logisticregression"]
logreg_coeffs = pd.DataFrame({
    "Feature": X_log.columns,
    "Coefficient": logreg_model.coef_[0]
}).sort_values("Coefficient", ascending=False)

print(logreg_coeffs)

# KNN REGRESSION
from sklearn.neighbors import KNeighborsRegressor
# Features and target
X_knn_reg = housing_cleaned.drop(
    ["RegionID", "RegionName", "RegionType", "StateName", "Sales_Count"],
    axis=1
)
y_knn_reg = housing_cleaned["Sales_Count"]


# Train/test split
X_train_knn_reg, X_test_knn_reg, y_train_knn_reg, y_test_knn_reg = train_test_split(
    X_knn_reg, y_knn_reg, test_size=0.2, random_state=42
)
# Pipeline: Imputer → Scaler → KNN Regressor
knn_reg_pipeline = make_pipeline(
    SimpleImputer(strategy="median"),
    MinMaxScaler(),
    KNeighborsRegressor(n_neighbors=5)
)
knn_reg_pipeline.fit(X_train_knn_reg, y_train_knn_reg)
y_pred_knn_reg = knn_reg_pipeline.predict(X_test_knn_reg)


print("\nKNN REGRESSION RESULTS")
print("R²:", r2_score(y_test_knn_reg, y_pred_knn_reg))


mse_knn = mean_squared_error(y_test_knn_reg, y_pred_knn_reg)
rmse_knn = mse_knn ** 0.5
print("RMSE:", rmse_knn)

# KNN CLASSIFICATION
housing_cleaned["High_Sales"] = (
    housing_cleaned["Sales_Count"] >= median_sales
).astype(int)
from sklearn.neighbors import KNeighborsClassifier


# Features and target
X_knn_clf = housing_cleaned.drop(
    ["RegionID", "RegionName", "RegionType", "StateName", "Sales_Count", "High_Sales"],
    axis=1
)
y_knn_clf = housing_cleaned["High_Sales"]
# Train/test split
X_train_knn_clf, X_test_knn_clf, y_train_knn_clf, y_test_knn_clf = train_test_split(
    X_knn_clf, y_knn_clf, test_size=0.2, random_state=42
)
# Pipeline: Imputer → Scaler → KNN Classifier
knn_clf_pipeline = make_pipeline(
    SimpleImputer(strategy="median"),
    MinMaxScaler(),
    KNeighborsClassifier(n_neighbors=5)
)
knn_clf_pipeline.fit(X_train_knn_clf, y_train_knn_clf)
y_pred_knn_clf = knn_clf_pipeline.predict(X_test_knn_clf)


print("\nKNN CLASSIFICATION RESULTS")
print("Confusion Matrix:\n", confusion_matrix(y_test_knn_clf, y_pred_knn_clf))
print("\nClassification Report:\n", classification_report(y_test_knn_clf, y_pred_knn_clf))


# Plot Confusion Matrix
class_names = ["Low Sales", "High Sales"]
disp = ConfusionMatrixDisplay.from_predictions(
    y_test_knn_clf,
    y_pred_knn_clf,

)
plt.xlabel("Predicted")                       # x-axis label
plt.ylabel("Actual")                            # y-axis label
plt.show()

# Filter the dataset to only include rows where RegionType == "MSA" (Metropolitan Statistical Area)
df_msa = housing_cleaned[housing_cleaned["RegionType"] == "msa"]

# Sort by Sales_Count
df_msa_sorted = df_msa.sort_values("Sales_Count", ascending=False)

# Define groups
top_10 = df_msa_sorted.iloc[:10]
top_100 = df_msa_sorted.iloc[10:100]  # next 90 MSAs
others = df_msa_sorted.iloc[100:]      # remaining MSAs

# Function to create scatterplots with two legend boxes
def plot_scatter_two_legends(x_col, title, x_label):
    plt.figure(figsize=(16,8))
    ax = plt.gca()  # get current axes

    # Plot Other MSAs
    sns.scatterplot(data=others, x=x_col, y="Sales_Count",
                    color="lightgrey", alpha=0.3, ax=ax)

    # Plot Top 100 group
    sns.scatterplot(data=top_100, x=x_col, y="Sales_Count",
                    color="green", s=70, ax=ax)

    # Plot Top 10 individually
    top10_colors = sns.color_palette("tab10", 10)
    top10_handles = []
    for i, (idx, row) in enumerate(top_10.iterrows()):
        sc = ax.scatter(row[x_col], row["Sales_Count"],
                        color=top10_colors[i], s=120)
        top10_handles.append(sc)

    # First legend: Top 10 MSAs
    top10_labels = list(top_10["RegionName"])
    legend1 = ax.legend(handles=top10_handles, labels=top10_labels, title="Top 10 MSAs",
                        bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=9)
    ax.add_artist(legend1)  # keep first legend visible

    # Second legend: Groups
    group_handles = [
        mpatches.Patch(color="green", label="Top 100 (excluding Top 10)"),
        mpatches.Patch(color="lightgrey", label="Other MSAs")
    ]
    ax.legend(handles=group_handles, title="Groups",
              bbox_to_anchor=(1.05, 0.5), loc='upper left', fontsize=9)

    plt.xlabel(x_label)
    plt.ylabel("Sales Count")
    plt.title(title)
    plt.tight_layout()
    plt.show()

# Demand vs Sales
# Higher numbers of pending listings strongly correspond to higher sales, showing that demand is the primary driver of housing transactions.
plot_scatter_two_legends("Newly_Pending_Listings",
                         "Demand vs Sales Count (Newly Pending Listings)",
                         "Newly Pending Listings")

# Supply vs Sales
# Greater inventory supports more sales, but supply alone does not guarantee high transaction volumes.
plot_scatter_two_legends("For-Sale_Inventory",
                         "Supply vs Sales Count (For-Sale Inventory)",
                         "For-Sale Inventory")

# Pricing vs Sales
# Higher median sale prices slightly limit sales in smaller metros, while large markets maintain strong sales despite high prices.
plot_scatter_two_legends("Median_Sale_Price",
                         "Pricing vs Sales Count (Median Sale Price)",
                         "Median Sale Price")

# Speed of Sales vs Sales
# Faster closings are associated with higher sales, indicating that market efficiency positively impacts transaction volume.
plot_scatter_two_legends("Median_Days_to_Close",
                         "Speed of Sales vs Sales Count",
                         "Median Days to Close")

# Correlation Heatmap
# Pending listings are most strongly correlated with sales, while inventory and speed have moderate effects and pricing shows a weak negative influence.
numeric_cols = ["For-Sale_Inventory", "New_Listings", "Newly_Pending_Listings",
                "Mean_Sale_Price", "Median_Sale_Price", "Home_Value_Index",
                "Median_Days_to_Close", "Sales_Count"]

plt.figure(figsize=(12,10), constrained_layout=True)
corr = df_msa_sorted[numeric_cols].corr()
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm")
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.title("Correlation Heatmap: Supply, Demand, Pricing vs Sales")
plt.show()

