# -*- coding: utf-8 -*-
"""HW_03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KyNU1vmWqd787kAatdocAIbgJ37SjsgM
"""

#import libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import mean_squared_error, r2_score, classification_report, confusion_matrix, ConfusionMatrixDisplay

def read_and_merge_csv(csv1, csv2, shared_column):    # TAKES two csv files and the name of their shared column, RETURNS a merged DataFrame of the two csv files
  df1 = pd.read_csv(csv1)                             # Reads the first csv file and stores it as DataFrame "df1"
  df2 = pd.read_csv(csv2)                             # Reads the second csv file and stores it as DataFrame "df2"
  merged_df = df1.merge(df2,on=shared_column)         # Merges "df1" and "df2" on "shared_column" and stores it as "merged_df"
  return merged_df

def clean_df(df):                                       # TAKES a DataFrame, RETURNS a cleaned version of the DataFrame without rows containing null/empty or 0 values
  deletes = []
  for a in df:                                          # Iterates through each title in the inputted DataFrame
    for b in range(len(df)):                            # Iterates through the number of rows in "df"
      try:
        if float(df[a][b]) == 0.0:                # If float of the value in column a, row b is 0.0 and if the row is not already in list "deletes", add row b to "deletes"
          if deletes.count(b) < 1:
            deletes.append(b)
      except:
        None

  df_cleaned = pd.DataFrame(data=df).drop(deletes)      # Drop the rows that contain 0s, which are stored in list "deletes", and store new DataFrame as "df_cleaned"
  df_cleaned = df_cleaned.dropna()                      # Drop null values in "df_cleaned"
  return df_cleaned

# PART 1 - Q1

def num_rows(df):       # TAKES in a DataFrame, RETURNS the number of rows
  return len(df)

# PART 1 - Q2

def age(df):                # TAKES a DataFrame, RETURNS the number of ages in the training set equal tO 14.5
  age_total = 0
  for c in df["age"]:       # Filters through all values in the "age" column of the DataFrame
    if c == 14.5:           # Selects "age" values equal to 14.5
      age_total += 1        # Adds one to the total count of ages equal to 14.5
  return age_total

# PART 1 - Q3

def list_abalone_values(df, ab_id):             # TAKES a DataFrame and abalone_id value, RETURNS list of values (not "sex" nor "abalone_id") in row with abalone_id "ab_id"
  lst1 = []
  for g in df:                                  # Iterates through titles in DataFrame "df"
    if g != "abalone_id" and g != "sex":        # Excludes columns "abalone_id" and "sex"
      lst1.append(float(df[g][ab_id-1]))        # Adds to an empty list the value in column g for the row with abalone_id "ab_id"
  return lst1

def euclidean_distance(list1, list2):           # TAKES in two lists, RETURNS the Euclidean Distance between the two lists (rounded to two decimal places)
  eu_dist = (sum((list1[d] - list2[d])**2 for d in range(len(list1))))**(1/2)
  return round(float(eu_dist),2)
pass

def manhattan_distance(list1, list2):           # TAKES in two lists, RETURNS the Manhattan Distance between the two lists (rounded to two decimal places)
  man_dist = sum(abs(list1[e] - list2[e]) for e in range(len(list1)))
  return round(float(man_dist),2)
pass

# PART 1 - Q4

def min_max_scale(df, lst):                  # TAKES a DataFrame and a list, RETURNS a Min-Max Scaled version of the list based on the scaled DataFrame
  df_values = []
  for a in df['abalone_id']:                 # Iterates through the values in the "abalone_id" column of the DataFrame
    row = []                                      # The empty list row is defined and reset for each new value of a
    for b in df:                             # Iterates through each column title of the DataFrame
      if b != "sex" and b != "abalone_id":        # Selects all columns other than "sex" and "abalone_id"
        row.append(float(df[b][a-1]))        # Adds to the list "row" the value in each column (not "sex" or "abalone_id") of a given row (row with "abalone_id" a)
    df_values.append(row)                           # Adds list "row" to list "ab_data" for each new value of a (each row), so each list within ab_data is a row (not "sex" or "abalone_id") of values from the DataFrame

  mms = MinMaxScaler()                            # Define MinMaxScaler() function
  mms.fit(df_values)                              # Fits data for scaler function to the list of values from the inputed DataFrame
  new_lst = mms.transform([lst])                  # Scales data in "lst" based on fitted scaler function
  new_lst = new_lst[0]                            # Unembeds "new_lst", the list of the list of scaled values in "lst"
  return new_lst

def euclidean_min_max(df, list1, list2):     # TAKES a Dataframe and two lists, RETURNS the Euclidean Distance between the Min-Max Scaled versions of the inputed lists
  list3 = min_max_scale(df, list1)           # Applies Min-Max Scaling to the first inputted list
  list4 = min_max_scale(df, list2)           # Applies Min-Max Scaling to the second inputted list
  return euclidean_distance(list3,list4)          # Takes and returns the Euclidean Distance of the scaled lists

def manhattan_min_max(df, list1, list2):     # TAKES a Dataframe and two lists, RETURNS the Manhattan Distance between the Min-Max Scaled versions of the inputed lists
  list3 = min_max_scale(df, list1)           # Applies Min-Max Scaling to the first inputted list
  list4 = min_max_scale(df, list2)           # Applies Min-Max Scaling to the second inputted list
  return manhattan_distance(list3,list4)          # Takes and returns the Manhattan Distance of the scaled lists

# PART 1 - Q5

def correlation(df):                     # TAKES a DataFrame, RETURNS the standard correlation matrix of the DataFrame's numerical feautures
  return df.corr(numeric_only=True)

def age_correlation(df):                     # TAKES a DataFrame, RETURNS the standard correlation matrix of the DataFrame's numerical feautures
  correl = correlation(df)
  titlesx = [i if i == "age" else "" for i in correl]                                             # List of titles for x-axis (only considering correlation for "age")
  titlesy = [i if i != "age" and i != "rings" and i != "abalone_id" else "" for i in correl]      # List of titles for y-axis (excludes the correlation of age, rings, abalone_id to age)
  correl_nums = []
  for h in range(len(correl)):                                                                    # Iterates through the number of rows in the correlation matrix
    for i in correl:                                                                              # Iterates through the titles in the correlation matrix
      correl_nums.append(round(float(correl[i].iloc[h]),2))                                       # Adds to an empty list the values in the correlation matrix by row
  strongest_correlation = ""
  weakest_correlation = ""
  for l in range(1,(len(correl)-2)):                                                # Iterates through number of rows correlated with age (not age, rings, abalone_id)
    if correl_nums[(9+10*l)] == max(correl_nums[19:(len(correl_nums)-20):10]):      # If a value in "age" column of correlation matrix = maximum value in the age_column (not age, rings, abalone_id)
      strongest_correlation = titlesy[l]                                              # Set "strongest_correlation" to the row title l on y-axis of the correlation matrix
    if correl_nums[(9+10*l)] == min(correl_nums[19:(len(correl_nums)-20):10]):      # If a value in "age" column of correlation matrix = minimum value in the age_column (not age, rings, abalone_id)
      weakest_correlation = titlesy[l]                                                # Set "weakest_correlation" to the row title l on y-axis of the correlation matrix
  return print("Strongest Correlation:\t", strongest_correlation, "\t\t", "Weakest Correlation:\t", weakest_correlation)


# PART 2 - Q1 (Q10)

def heatmap_and_age_corr(df):             # TAKES a DataFrame, RETURNS a heatmap of the standard correlation matrix and which numerical features have the strongest and weakest correlation with age
  correl = correlation(df)
  titlesx = [i if i == "age" else "" for i in correl]                                             # List of titles for x-axis (only considering correlation for "age")
  titlesy = [i if i != "age" and i != "rings" and i != "abalone_id" else "" for i in correl]      # List of titles for y-axis (excludes the correlation of age, rings, abalone_id to age)
  fig, axis = plt.subplots()                                                      # Defining a figure and its subplots/axes
  axis.imshow(correl)                                                             # Plots the inputted correlation matrix
  correl_nums = []
  for h in range(len(correl)):                                                    # Iterates through the number of rows in the correlation matrix
    for i in correl:                                                              # Iterates through the titles in the correlation matrix
      correl_nums.append(round(float(correl[i].iloc[h]),2))                       # Adds to an empty list the values in the correlation matrix by row
  for j in range(len(correl)):                                                    # Iterates through the number of rows in the correlation matrix
    for k in range(len(correl)):                                                  # Iterates through the number of rows in the correlation matrix
      text = axis.text(x=(k-.35), y=(j+.1), s=(correl_nums[k+10*j]))              # Adds the value (s) in the inputted correlation matrix at coordinate (x,y) by row
  axis.set_xticks(range(len(titlesx)),labels=titlesx)                             # Sets the x-axis labels based on the labels list "titlesx"
  axis.set_yticks(range(len(titlesy)),labels=titlesy)                             # Sets the y-axis labels based on the labels list "titlesy"
  y_val1 = 0
  y_val2 = 0
  for l in range(1,(len(correl)-2)):                                                # Iterates through number of rows correlated with age (not age, rings, abalone_id)
    if correl_nums[(9+10*l)] == max(correl_nums[19:(len(correl_nums)-20):10]):      # If a value in "age" column of correlation matrix = maximum value in the age_column (not age, rings, abalone_id)
      y_val1 = l                                                                      # Set "y_val1" to row l on y-axis of the correlation matrix
    if correl_nums[(9+10*l)] == min(correl_nums[19:(len(correl_nums)-20):10]):      # If a value in "age" column of correlation matrix = minimum value in the age_column (not age, rings, abalone_id)
      y_val2 = l                                                                      # Set "y_val2" to row l on y-axis of the correlation matrix
  axis.text(x=(len(correl)),y=(y_val1),s="strongest correlation")                   # Adds text "strongest correlation" at point (x,y)
  axis.text(x=(len(correl)),y=(y_val2),s="weakest correlation")                     # Adds text "weakest correlation" at point (x,y)
  plt.show()

# PART 1 - Q6

def mean_sq_err_and_r2_score(dftrain, dftest):                  # TAKES a training and test set, RETURNS the mean squared error and the r2-score based on the test set
  x_tr1 = dftrain[["shell_weight"]].values                      # Defines x_train
  y_tr1 = dftrain["age"].values                                 # Defines y_train
  x_te1 = dftest[["shell_weight"]].values                       # Defines x_test
  y_te1 = dftest["age"].values                                  # Defines y_test

  model1 = LinearRegression()                                   # Define LinearRegression() function
  model1.fit(x_tr1,y_tr1)                                       # Fits data for linear regression
  y_pred1 = model1.predict(x_te1)                               # Predicts age based on test values of shell weight
  mean_sq_err = round(mean_squared_error(y_te1, y_pred1),2)     # Calculates and rounds mean squared error of age test value and predicted age
  r2_sc = round(r2_score(y_te1, y_pred1),2)                     # Calculates and rounds r2-score of age test value and predicted age

  return (mean_sq_err, r2_sc)

# PART 1 - Q7

def KNN_Class_I(dftrain, dftest):                     # TAKES a training and test set, RETURNS the number of "I"s correctly predicted in the testing set
  x_tr2 = dftrain[[i for i in correlation(dftrain) if i != "sex" and i != "abalone_id" and i != "age"]].values    # Defines x_train
  y_tr2 = dftrain["sex"].values                                                                                   # Defines y_train
  x_te2 = dftest[[i for i in correlation(dftrain) if i != "sex" and i != "abalone_id" and i != "age"]].values     # Defines x_test
  y_te2 = dftest["sex"].values                                                                                    # Defines y_test

  model2 = KNeighborsClassifier(n_neighbors=2)    # Define KNeighborsClassifier() function with number of nearest neighbors considered as 2
  model2.fit(x_tr2, y_tr2)                        # Fits data for KNN Classifier
  y_pred2 = model2.predict(x_te2)                 # Predicts sex based on test values
  c_matrix = confusion_matrix(y_te2,y_pred2)      # Creates a confusion matrix from "sex" in the test set and the oredicted values of "sex"
  KNN_I = int(c_matrix[1][1])                     # Assigns the True Positive value of "I"
  return KNN_I

# PART 1 - Q8

def KNN_Class_F(dftrain, dftest):                         # TAKES a training and test set, RETURNS the classification report and f1-score for "F" based on the testing set
  x_tr2 = dftrain[[i for i in correlation(dftrain) if i != "sex" and i != "abalone_id" and i != "age"]].values    # Defines x_train
  y_tr2 = dftrain["sex"].values                                                                                   # Defines y_train
  x_te2 = dftest[[i for i in correlation(dftrain) if i != "sex" and i != "abalone_id" and i != "age"]].values     # Defines x_test
  y_te2 = dftest["sex"].values                                                                                    # Defines y_test

  model2 = KNeighborsClassifier(n_neighbors=6)            # Define KNeighborsClassifier() function with number of nearest neighbors considered as 6
  model2.fit(x_tr2, y_tr2)                                # Fits data for KNN Classifier
  y_pred2 = model2.predict(x_te2)                         # Predicts sex based on test values
  class_rep = classification_report(y_te2, y_pred2)       # Create a classification report based on "sex" test values and predicted "sex"
  return print(class_rep,
               "F1-score for 'F':", class_rep[94:98])

# PART 1 - Q9

def K_value(dftrain, dftest, k):                        # TAKES a training set, test set, and number of nearest-neighbors k, RETURNS classification report and inputted k
  x_tr2 = dftrain[[i for i in correlation(dftrain) if i != "sex" and i != "abalone_id" and i != "age"]].values    # Defines x_train
  y_tr2 = dftrain["sex"].values                                                                                   # Defines y_train
  x_te2 = dftest[[i for i in correlation(dftrain) if i != "sex" and i != "abalone_id" and i != "age"]].values     # Defines x_test
  y_te2 = dftest["sex"].values                                                                                    # Defines y_test

  model2 = KNeighborsClassifier(n_neighbors=k)          # Define KNeighborsClassifier() function with number of nearest-neighbors considered as k
  model2.fit(x_tr2, y_tr2)                              # Fits data for KNN Classifier
  y_pred2 = model2.predict(x_te2)                       # Predicts sex based on test values
  class_rep = classification_report(y_te2, y_pred2)     # Create a classification report based on "sex" test values and predicted "sex"
  return print(class_rep,
               "Value of K:\t", k)

# PART 2 - Q2 (Q11)

def lin_reg_y_pred(dftrain, dftest):                # TAKES a training and test set, RETURNS "shell_weight" and "age" test values and predicted "age" based on the test set
  x_tr = dftrain[["shell_weight"]].values           # Defines x_train
  y_tr = dftrain["age"].values                      # Defines y_train
  x_te = dftest[["shell_weight"]].values            # Defines x_test
  y_te = dftest["age"].values                     # Defines y_test

  model = LinearRegression()                        # Define LinearRegression() function
  model.fit(x_tr,y_tr)                              # Fits data for linear regression
  y_pred = model.predict(x_te)                      # Predicts age based on test values of shell weight
  return x_te, y_te, y_pred

def age_plot(dftrain, dftest):                                            # TAKES a training and test set, RETURNS a scatter plot of actual versus predicted age
  x_test, age_actual, age_pred = lin_reg_y_pred(dftrain, dftest)          # Defines "shell_weight" as "x_test", x_test "age" as "age_actual" and predicted "age" based on the test set as "age_pred"

  plt.scatter(x_test, age_actual, color="green", label="Actual")          # Creates a scatter plot of "shell_weight" on the x-axis and "age_actual" on the y-axis
  plt.scatter(x_test, age_pred, color="orange", label="Predicted")        # Adds "age_pred" to the y-axis of the scatter plot
  plt.legend()
  plt.xlabel("Shell Weight")
  plt.ylabel("Age")
  plt.title("Actual Age vs. Predicted Age (Test Set)")
  plt.grid(True)
  plt.show()

# PART 2 - Q3 (Q12)

def KNN_heatmap(dftrain, dftest):                     # TAKES a training and test set, RETURNS a heatmap of the confusion_matrix from KNN Classifier with nearest-neighbors=9
  x_tr3 = dftrain[[i for i in correlation(dftrain) if i != "sex" and i != "abalone_id" and i != "age"]].values      # Defines x_train
  y_tr3 = dftrain["sex"].values                                                                                     # Defines y_train
  x_te3 = dftest[[i for i in correlation(dftrain) if i != "sex" and i != "abalone_id" and i != "age"]].values       # Defines x_test
  y_te3 = dftest["sex"].values                                                                                      # Defines y_test

  model3 = KNeighborsClassifier(n_neighbors=9)        # Define KNeighborsClassifier() function with number of nearest-neighbors considered as 9
  model3.fit(x_tr3, y_tr3)                            # Fits data for KNN Classifier
  y_pred3 = model3.predict(x_te3)                     # Predicts "sex" based on test values
  c_matrix = confusion_matrix(y_te3, y_pred3)         # Creates a confusion matrix based on the test values and predicted values of "sex"
  c_matrix_display = ConfusionMatrixDisplay(confusion_matrix=c_matrix, display_labels=["F", "I", "M"])        # Converts the confusion matrix into a heatmap
  c_matrix_display.plot()
  plt.show()

def main():
  abalone_data = read_and_merge_csv('abalone_labels.csv', 'abalone_measurements.csv', "abalone_id")
  abalone_cleaned = clean_df(abalone_data)
  abalone_cleaned.insert(10, "age", (abalone_cleaned["rings"]+1.5))
  df_train, df_test = train_test_split(abalone_cleaned, test_size=0.2, random_state=0)

  # Q1 - calling
  print('\nQ1')
  df_rows = num_rows(abalone_cleaned)
  print(f"Number of rows in cleaned DataFrame:   {df_rows}")

  # Q2 - calling
  print('\nQ2')
  abalone_age = age(df_train)
  print(f"Number of abalones of age 14.5:    {abalone_age}")

  # Q3 - calling
  print('\nQ3')
  eu_dist = euclidean_distance((list_abalone_values(abalone_cleaned, 179)), (list_abalone_values(abalone_cleaned, 3897)))
  man_dist = manhattan_distance((list_abalone_values(abalone_cleaned, 179)), (list_abalone_values(abalone_cleaned, 3897)))
  print(f"Euclidean Distance between abalone 179 and abalone 3897:   {eu_dist}")
  print(f"Manhattan Distance between abalone 179 and abalone 3897:   {man_dist}")

  # Q4 - calling
  print('\nQ4')
  eu_dist_scaled = euclidean_min_max(df_train, (list_abalone_values(abalone_cleaned, 179)), (list_abalone_values(abalone_cleaned, 3897)))
  man_dist_scaled = manhattan_min_max(df_train, (list_abalone_values(abalone_cleaned, 179)), (list_abalone_values(abalone_cleaned, 3897)))
  print(f"Euclidean Distance between abalone 179 and abalone 3897:   {eu_dist_scaled}")
  print(f"Manhattan Distance between abalone 179 and abalone 3897:   {man_dist_scaled}")

  # Q5 - calling
  print('\nQ5')
  print("Features correlated with age:")
  age_corr = age_correlation(df_train)

  # Q6 - calling
  print('\nQ6')
  mean_sq_error, r2_score_value = mean_sq_err_and_r2_score(df_train, df_test)
  print(f"Mean Squared Error:    {mean_sq_error}")
  print(f"R-Squared Value:    {r2_score_value}")

  # Q7 - calling
  print('\nQ7')
  KNN_I = KNN_Class_I(df_train, df_test)
  print(f"Correctly predicted 'I's:    {KNN_I}")

  # Q8 - calling
  print('\nQ8')
  KNN_F = KNN_Class_F(df_train, df_test)

  # Q9 - calling
  print('\nQ9')
  print(f"Value of k with highest accuracy:    9")
  K_val3, K_val5, K_val7 = K_value(df_train, df_test, 3), K_value(df_train, df_test, 5), K_value(df_train, df_test, 7)
  K_val9, K_val11 = K_value(df_train, df_test, 9), K_value(df_train, df_test, 11)

  # Q10 - calling
  print('\nQ10')
  print(f"Heatmap of Age Correlation:")
  age_heatmap = heatmap_and_age_corr(df_train)

  # Q11 - calling
  print('\nQ11')
  print(f"Actual vs. Predicted Age Scatter Plot:")
  age_scatter = age_plot(df_train, df_test)

  # Q12 - calling
  print('\nQ12')
  print(f"Heatmap of Confusion Matrix:")
  KNN_map = KNN_heatmap(df_train, df_test)


if __name__ == "__main__":
    main()