# -*- coding: utf-8 -*-
"""Lab 04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jMEgLicvjR5COX_POaWwhLEY4Sw_ZpWt
"""

# LAB EXERCISE 04

# PROBLEM 01
def problem1(lst):
  if lst == []:
    return "empty list"
  else:
    return lst[(len(lst)-1)]

# PROBLEM 02
def problem2(num):
  n = 0
  st = ""
  while n < num:
    n += 1
    st += str(n)
  return st

# PROBLEM 03
def problem3(lst1,lst2):
  lst3 = []
  for a in lst1:
    st1 = a
    for b in lst2:
      st1 += b
    lst3.append(st1)
  return lst3

# PROBLEM 04
def problem4(lst4):
  lst5 = sorted(lst4, key=(lambda x: x[1]))
  return lst5

#EXTRA PROBLEM 01
def extra_p1(lst6):
  st2 = ""
  for a in lst6:
    st2 += str(a)
  return st2

#EXTRA PROBLEM 02
class Counter():
  def __init__(self, val):
    self.val = val
  def increment(self, val2):
    self.val += val2

count = Counter(1)
count.increment(10)
count.increment(100)
print(count.val)

#EXTRA PROBLEM 03
[1,2,3,4]
[10,20,30]

#EXTRA PROBLEM 04
#1. True
#2. False
#3. False
#4. True *
#5. False
#6. True
#7. False
#8. False *
#9. True
#10. True
#11. True
#12. True
#13. False *
#14. True