# -*- coding: utf-8 -*-
"""Lab 06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13vqJsCV4paytuZoGfhcnlWxcPZ3GXe2-
"""

# PROBLEM 1

def find_average(lst1):
  if lst1 == []:
    return None
  else:
    mean = sum(lst1)/(len(lst1))
    return mean

# PROBLEM 2

def find_median(lst2):
  if lst2 == []:
    return None
  else:
    while len(lst2) > 2:
      lst2.remove(lst2[0])
      lst2.remove(lst2[(len(lst2)-1)])
    med = sum(lst2)/len(lst2)
    return med

# PROBLEM 3

def find_mode(lst3):
  if lst3 == []:
    return None
  else:
    counts = []
    mode = []
    for a in lst3:
      counts.append(lst3.count(a))
    for b in range(len(lst3)):
      if counts[b] == max(counts):
        mode.append(lst3[b])
    if len(mode) == 1:
      return mode[0]
    else:
      for c in mode:
        while mode.count(c) > 1:
          mode.remove(c)
      if len(mode) == 1:
        return mode[0]
      else:
        return mode

# PROBLEM 4

def find_variance(lst4):
  if lst4 == []:
    return None
  else:
    avg = find_average(lst4)
    var = 0
    for i in lst4:
      var += ((i-avg)**2)/len(lst4)
    return var

# EXTRA PROBLEM 1

# Scatter Plot:       Hours Studied and Score
# Bar Plot:       Hours Studied and Score, Result and Hours Studied
# Box Plot:       Hours Studied and Score, Result and Hours Studied