# -*- coding: utf-8 -*-
"""Lab 08

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sVmebBcWfFyOwXpa8cdQJTAGrQjsU_jA
"""

# LAB EXERCISE 08

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
df = pd.read_csv("lab08_data.csv")

# PROBLEM 01
# df_tr = train_test_split(df,test_size=0.2,random_state=2500)[0]
# df_te = train_test_split(df,test_size=0.2,random_state=2500)[1]

df_tr, df_te = train_test_split(df,test_size=0.2,random_state=2500)

# PROBLEM 02

corr_matrix = df_tr.corr()
corr_matrix

# PROBLEM 03
X_train = df_tr[["X2"]].values
Y_train = df_tr["y"].values

model = LinearRegression()
model.fit(X_train, Y_train)
w = model.coef_[0]
b = model.intercept_

{w,b}

# PROBLEM 04
X_test = df_te[["X2"]].values
Y_test = df_te["y"].values

Y_pred_tr = model.predict(X_train)
mse_tr = mean_squared_error(Y_train, Y_pred_tr)
r2_tr = r2_score(Y_train, Y_pred_tr)

Y_pred_te = model.predict(X_test)
mse_te = mean_squared_error(Y_test, Y_pred_te)
r2_te = r2_score(Y_test, Y_pred_te)

print({mse_tr}, {r2_tr},
      {mse_te}, {r2_te})